-- Baseline migration for ResearchCrafters.
--
-- Authored manually to mirror packages/db/prisma/schema.prisma 1:1 without
-- requiring a live Postgres for `prisma migrate dev`. Apply with:
--   pnpm --filter @researchcrafters/db exec prisma migrate deploy
-- against the docker-compose Postgres.
--
-- Conventions:
--   * cuid() ids are generated by the application; columns are plain TEXT.
--   * JSON columns use JSONB so Prisma's `Json` mapping works.
--   * Postgres String[] (text[]) is used for primitive arrays.
--   * Cascading delete semantics mirror the `onDelete` annotations in
--     schema.prisma; `Restrict` maps to `ON DELETE RESTRICT`.

-- =============================================================================
-- User & auth
-- =============================================================================

CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "githubHandle" TEXT,
    "displayName" TEXT,
    "name" TEXT,
    "image" TEXT,
    "emailVerified" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_createdAt_idx" ON "User"("createdAt");

CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key"
    ON "Account"("provider", "providerAccountId");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
ALTER TABLE "Account"
    ADD CONSTRAINT "Account_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
ALTER TABLE "Session"
    ADD CONSTRAINT "Session_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "DeviceCodeFlow" (
    "id" TEXT NOT NULL,
    "deviceCode" TEXT NOT NULL,
    "userCode" TEXT NOT NULL,
    "userId" TEXT,
    "state" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "consumedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DeviceCodeFlow_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "DeviceCodeFlow_deviceCode_key" ON "DeviceCodeFlow"("deviceCode");
CREATE UNIQUE INDEX "DeviceCodeFlow_userCode_key" ON "DeviceCodeFlow"("userCode");
CREATE INDEX "DeviceCodeFlow_state_expiresAt_idx" ON "DeviceCodeFlow"("state", "expiresAt");
ALTER TABLE "DeviceCodeFlow"
    ADD CONSTRAINT "DeviceCodeFlow_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key"
    ON "VerificationToken"("identifier", "token");

-- =============================================================================
-- Membership & entitlement
-- =============================================================================

CREATE TABLE "Membership" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "plan" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "billingRef" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Membership_userId_idx" ON "Membership"("userId");
CREATE INDEX "Membership_status_idx" ON "Membership"("status");
ALTER TABLE "Membership"
    ADD CONSTRAINT "Membership_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "Entitlement" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "packageVersionId" TEXT,
    "stageId" TEXT,
    "source" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Entitlement_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Entitlement_userId_scope_idx" ON "Entitlement"("userId", "scope");
CREATE INDEX "Entitlement_packageVersionId_idx" ON "Entitlement"("packageVersionId");
CREATE INDEX "Entitlement_stageId_idx" ON "Entitlement"("stageId");

-- =============================================================================
-- Packages, versions, patches
-- =============================================================================

CREATE TABLE "Package" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Package_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Package_slug_key" ON "Package"("slug");

CREATE TABLE "PackageVersion" (
    "id" TEXT NOT NULL,
    "packageId" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "sourceHash" TEXT NOT NULL,
    "manifest" JSONB NOT NULL,
    "releaseFreeStageIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "requiresGpu" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PackageVersion_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PackageVersion_packageId_version_key"
    ON "PackageVersion"("packageId", "version");
CREATE INDEX "PackageVersion_status_idx" ON "PackageVersion"("status");
ALTER TABLE "PackageVersion"
    ADD CONSTRAINT "PackageVersion_packageId_fkey"
    FOREIGN KEY ("packageId") REFERENCES "Package"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "PackageVersionPatch" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "patchSeq" INTEGER NOT NULL,
    "overlays" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PackageVersionPatch_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PackageVersionPatch_packageVersionId_patchSeq_key"
    ON "PackageVersionPatch"("packageVersionId", "patchSeq");
CREATE INDEX "PackageVersionPatch_packageVersionId_idx"
    ON "PackageVersionPatch"("packageVersionId");
ALTER TABLE "PackageVersionPatch"
    ADD CONSTRAINT "PackageVersionPatch_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- Mirrored package contents
-- =============================================================================

CREATE TABLE "Stage" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "stageId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "difficulty" TEXT NOT NULL,
    "estimatedTimeMinutes" INTEGER NOT NULL,
    "validationKind" TEXT NOT NULL,
    "runnerMode" TEXT NOT NULL,
    "rubricRef" TEXT,
    "stagePolicy" JSONB NOT NULL,
    "passThreshold" DOUBLE PRECISION,
    "free" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Stage_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Stage_packageVersionId_stageId_key"
    ON "Stage"("packageVersionId", "stageId");
CREATE INDEX "Stage_packageVersionId_stageId_idx"
    ON "Stage"("packageVersionId", "stageId");
ALTER TABLE "Stage"
    ADD CONSTRAINT "Stage_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Entitlement"
    ADD CONSTRAINT "Entitlement_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Entitlement"
    ADD CONSTRAINT "Entitlement_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Entitlement"
    ADD CONSTRAINT "Entitlement_stageId_fkey"
    FOREIGN KEY ("stageId") REFERENCES "Stage"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "DecisionNode" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "nodeId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "stageRef" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DecisionNode_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "DecisionNode_packageVersionId_nodeId_key"
    ON "DecisionNode"("packageVersionId", "nodeId");
CREATE INDEX "DecisionNode_packageVersionId_nodeId_idx"
    ON "DecisionNode"("packageVersionId", "nodeId");
ALTER TABLE "DecisionNode"
    ADD CONSTRAINT "DecisionNode_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "Branch" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "decisionNodeId" TEXT,
    "branchId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "supportLevel" TEXT NOT NULL,
    "choice" TEXT NOT NULL,
    "evidenceRefs" JSONB NOT NULL,
    "sourceRefs" JSONB,
    "lesson" TEXT NOT NULL,
    "gatedFeedbackVisibility" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Branch_packageVersionId_branchId_key"
    ON "Branch"("packageVersionId", "branchId");
CREATE INDEX "Branch_packageVersionId_branchId_idx"
    ON "Branch"("packageVersionId", "branchId");
CREATE INDEX "Branch_decisionNodeId_idx" ON "Branch"("decisionNodeId");
ALTER TABLE "Branch"
    ADD CONSTRAINT "Branch_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Branch"
    ADD CONSTRAINT "Branch_decisionNodeId_fkey"
    FOREIGN KEY ("decisionNodeId") REFERENCES "DecisionNode"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- =============================================================================
-- Learner progress
-- =============================================================================

CREATE TABLE "Enrollment" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "activeStageRef" TEXT,
    "completedStageRefs" JSONB NOT NULL DEFAULT '[]',
    "unlockedNodeRefs" JSONB NOT NULL DEFAULT '[]',
    "status" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Enrollment_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Enrollment_userId_packageVersionId_idx"
    ON "Enrollment"("userId", "packageVersionId");
CREATE INDEX "Enrollment_packageVersionId_idx" ON "Enrollment"("packageVersionId");
CREATE INDEX "Enrollment_status_idx" ON "Enrollment"("status");
ALTER TABLE "Enrollment"
    ADD CONSTRAINT "Enrollment_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Enrollment"
    ADD CONSTRAINT "Enrollment_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "NodeTraversal" (
    "id" TEXT NOT NULL,
    "enrollmentId" TEXT NOT NULL,
    "decisionNodeId" TEXT NOT NULL,
    "branchId" TEXT,
    "selectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NodeTraversal_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "NodeTraversal_enrollmentId_idx" ON "NodeTraversal"("enrollmentId");
CREATE INDEX "NodeTraversal_decisionNodeId_idx" ON "NodeTraversal"("decisionNodeId");
ALTER TABLE "NodeTraversal"
    ADD CONSTRAINT "NodeTraversal_enrollmentId_fkey"
    FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NodeTraversal"
    ADD CONSTRAINT "NodeTraversal_decisionNodeId_fkey"
    FOREIGN KEY ("decisionNodeId") REFERENCES "DecisionNode"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "NodeTraversal"
    ADD CONSTRAINT "NodeTraversal_branchId_fkey"
    FOREIGN KEY ("branchId") REFERENCES "Branch"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "StageAttempt" (
    "id" TEXT NOT NULL,
    "enrollmentId" TEXT NOT NULL,
    "stageRef" TEXT NOT NULL,
    "answer" JSONB NOT NULL,
    "branchId" TEXT,
    "score" DOUBLE PRECISION,
    "passed" BOOLEAN NOT NULL DEFAULT false,
    "executionStatus" TEXT,
    "gradeId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StageAttempt_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "StageAttempt_enrollmentId_stageRef_idx"
    ON "StageAttempt"("enrollmentId", "stageRef");
CREATE INDEX "StageAttempt_createdAt_idx" ON "StageAttempt"("createdAt");
ALTER TABLE "StageAttempt"
    ADD CONSTRAINT "StageAttempt_enrollmentId_fkey"
    FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StageAttempt"
    ADD CONSTRAINT "StageAttempt_branchId_fkey"
    FOREIGN KEY ("branchId") REFERENCES "Branch"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "Submission" (
    "id" TEXT NOT NULL,
    "stageAttemptId" TEXT NOT NULL,
    "bundleObjectKey" TEXT NOT NULL,
    "bundleSha" TEXT NOT NULL,
    "byteSize" INTEGER NOT NULL,
    "fileCount" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Submission_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Submission_stageAttemptId_idx" ON "Submission"("stageAttemptId");
CREATE INDEX "Submission_bundleSha_idx" ON "Submission"("bundleSha");
ALTER TABLE "Submission"
    ADD CONSTRAINT "Submission_stageAttemptId_fkey"
    FOREIGN KEY ("stageAttemptId") REFERENCES "StageAttempt"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "Run" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "runnerMode" TEXT NOT NULL,
    "logObjectKey" TEXT,
    "metricsJson" JSONB,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Run_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Run_submissionId_idx" ON "Run"("submissionId");
CREATE INDEX "Run_status_createdAt_idx" ON "Run"("status", "createdAt");
ALTER TABLE "Run"
    ADD CONSTRAINT "Run_submissionId_fkey"
    FOREIGN KEY ("submissionId") REFERENCES "Submission"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "Grade" (
    "id" TEXT NOT NULL,
    "stageAttemptId" TEXT NOT NULL,
    "submissionId" TEXT,
    "rubricVersion" TEXT NOT NULL,
    "evaluatorVersion" TEXT NOT NULL,
    "passed" BOOLEAN NOT NULL DEFAULT false,
    "score" DOUBLE PRECISION,
    "dimensions" JSONB NOT NULL,
    "evidenceRefs" JSONB NOT NULL,
    "modelMeta" JSONB,
    "history" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Grade_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Grade_submissionId_rubricVersion_evaluatorVersion_key"
    ON "Grade"("submissionId", "rubricVersion", "evaluatorVersion");
CREATE INDEX "Grade_stageAttemptId_idx" ON "Grade"("stageAttemptId");
CREATE INDEX "Grade_createdAt_idx" ON "Grade"("createdAt");
ALTER TABLE "Grade"
    ADD CONSTRAINT "Grade_stageAttemptId_fkey"
    FOREIGN KEY ("stageAttemptId") REFERENCES "StageAttempt"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Grade"
    ADD CONSTRAINT "Grade_submissionId_fkey"
    FOREIGN KEY ("submissionId") REFERENCES "Submission"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- =============================================================================
-- Mentor
-- =============================================================================

CREATE TABLE "MentorThread" (
    "id" TEXT NOT NULL,
    "enrollmentId" TEXT NOT NULL,
    "stageRef" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MentorThread_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "MentorThread_enrollmentId_stageRef_idx"
    ON "MentorThread"("enrollmentId", "stageRef");
ALTER TABLE "MentorThread"
    ADD CONSTRAINT "MentorThread_enrollmentId_fkey"
    FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "MentorMessage" (
    "id" TEXT NOT NULL,
    "threadId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "bodyText" TEXT NOT NULL,
    "modelTier" TEXT,
    "modelId" TEXT,
    "provider" TEXT,
    "promptTokens" INTEGER,
    "completionTokens" INTEGER,
    "redactionTriggered" BOOLEAN NOT NULL DEFAULT false,
    "flagged" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MentorMessage_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "MentorMessage_threadId_createdAt_idx"
    ON "MentorMessage"("threadId", "createdAt");
CREATE INDEX "MentorMessage_flagged_idx" ON "MentorMessage"("flagged");
ALTER TABLE "MentorMessage"
    ADD CONSTRAINT "MentorMessage_threadId_fkey"
    FOREIGN KEY ("threadId") REFERENCES "MentorThread"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- Analytics & sharing
-- =============================================================================

CREATE TABLE "BranchStat" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "decisionNodeId" TEXT NOT NULL,
    "branchId" TEXT NOT NULL,
    "cohort" TEXT NOT NULL,
    "windowStart" TIMESTAMP(3) NOT NULL,
    "windowEnd" TIMESTAMP(3) NOT NULL,
    "n" INTEGER NOT NULL,
    "percent" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BranchStat_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "BranchStat_packageVersionId_decisionNodeId_branchId_cohort__idx"
    ON "BranchStat"("packageVersionId", "decisionNodeId", "branchId", "cohort", "windowStart");
ALTER TABLE "BranchStat"
    ADD CONSTRAINT "BranchStat_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BranchStat"
    ADD CONSTRAINT "BranchStat_decisionNodeId_fkey"
    FOREIGN KEY ("decisionNodeId") REFERENCES "DecisionNode"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ShareCard" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "enrollmentId" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "publicSlug" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ShareCard_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ShareCard_publicSlug_key" ON "ShareCard"("publicSlug");
CREATE INDEX "ShareCard_userId_idx" ON "ShareCard"("userId");
CREATE INDEX "ShareCard_enrollmentId_idx" ON "ShareCard"("enrollmentId");
CREATE INDEX "ShareCard_packageVersionId_idx" ON "ShareCard"("packageVersionId");
ALTER TABLE "ShareCard"
    ADD CONSTRAINT "ShareCard_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShareCard"
    ADD CONSTRAINT "ShareCard_enrollmentId_fkey"
    FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShareCard"
    ADD CONSTRAINT "ShareCard_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "Review" (
    "id" TEXT NOT NULL,
    "packageVersionId" TEXT NOT NULL,
    "reviewerId" TEXT,
    "status" TEXT NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Review_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Review_packageVersionId_idx" ON "Review"("packageVersionId");
CREATE INDEX "Review_status_idx" ON "Review"("status");
ALTER TABLE "Review"
    ADD CONSTRAINT "Review_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Review"
    ADD CONSTRAINT "Review_reviewerId_fkey"
    FOREIGN KEY ("reviewerId") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "Event" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "userId" TEXT,
    "packageVersionId" TEXT,
    "stageRef" TEXT,
    "payload" JSONB NOT NULL,
    "auditGrade" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Event_name_createdAt_idx" ON "Event"("name", "createdAt");
CREATE INDEX "Event_userId_createdAt_idx" ON "Event"("userId", "createdAt");
CREATE INDEX "Event_auditGrade_createdAt_idx" ON "Event"("auditGrade", "createdAt");
ALTER TABLE "Event"
    ADD CONSTRAINT "Event_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Event"
    ADD CONSTRAINT "Event_packageVersionId_fkey"
    FOREIGN KEY ("packageVersionId") REFERENCES "PackageVersion"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
