from __future__ import annotations

from pathlib import Path
import shutil

from .inputs import title_from_slug


TEXT_SUFFIXES = {
    ".md",
    ".py",
    ".txt",
    ".yaml",
    ".yml",
}


def copy_template_package(
    *,
    template_path: Path,
    package_path: Path,
    slug: str,
    title: str,
) -> list[str]:
    if not template_path.is_dir():
        raise FileNotFoundError(f"Template path does not exist: {template_path}")
    if package_path.exists():
        raise FileExistsError(f"Package path already exists: {package_path}")
    package_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(template_path, package_path)
    replacements = _replacements(slug, title)
    generated: list[str] = []
    for file_path in sorted(path for path in package_path.rglob("*") if path.is_file()):
        rel = file_path.relative_to(package_path).as_posix()
        generated.append(rel)
        if file_path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        try:
            text = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for old, new in replacements.items():
            text = text.replace(old, new)
        file_path.write_text(text, encoding="utf-8")
    _write_generated_readme(package_path / "README.md", slug, title)
    return generated


def _replacements(slug: str, title: str) -> dict[str, str]:
    short_title = title_from_slug(slug)
    return {
        "TODO_paper_slug": slug,
        "TODO_paper_title": title,
        "TODO_skill_1": "paper reconstruction",
        "TODO_skill_2": "evidence analysis",
        "TODO_prerequisite_1": "Read the source paper",
        "TODO_canonical_phrase": f"{slug} canonical answer placeholder",
        "TODO_framing_title": f"Frame {short_title}",
        "TODO_canonical_feedback": "A strong answer grounds the paper goal in a concrete research problem and cites the supporting artifact.",
        "TODO_misconception_1": "Summarizing the abstract without naming the research decision the learner will practice.",
    }


def _write_generated_readme(path: Path, slug: str, title: str) -> None:
    path.write_text(
        "\n".join(
            [
                f"# {title}",
                "",
                "Draft ERP package generated by `apps/erp-agent`.",
                "",
                "This is an alpha authoring scaffold. It preserves the normal",
                "`content/packages/<slug>/` package contract and must pass",
                "`researchcrafters validate` before human expert review.",
                "",
                "## Current Scope",
                "",
                "- Template-backed package structure.",
                "- Initial framing stage, rubric, hints, runner config, and safety policy.",
                "- Placeholder ARA files that must be replaced during paper reconstruction.",
                "",
                "## Review Blockers",
                "",
                "- Replace placeholder metadata and artifact files with source-grounded content.",
                "- Add failed, suboptimal, ambiguous, or extension branches after the happy path validates.",
                "- Calibrate evidence support levels and redaction targets before beta/live promotion.",
                "",
                f"Package slug: `{slug}`",
                "",
            ]
        ),
        encoding="utf-8",
    )
